"""Compile Sigma YAML rules to Wazuh XML (and optionally KQL).

Usage:
    python scripts/compile_sigma.py \
        --in detections/sigma \
        --out-wazuh detections/wazuh-rules/_generated

pySigma doesn't ship a first-party Wazuh backend; we use a small custom
mapper that handles the common cases (Keycloak events, syslog, file integrity).
For complex rules you may need to hand-tune the XML.

This script is intentionally simple. Extend as your detection coverage grows.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Install pyyaml: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


WAZUH_RULE_TEMPLATE = """<group name="ouroboros,{tags}">
  <rule id="{rule_id}" level="{level}">
    <if_sid>{parent_sid}</if_sid>
    <description>{description}</description>
    <mitre>
{mitre_blocks}
    </mitre>
    {match_block}
  </rule>
</group>
"""


def _sigma_to_wazuh(sigma_doc: dict, numeric_id: int) -> str:
    title = sigma_doc.get("title", "Untitled")
    description = title.replace("\n", " ")
    level_map = {"low": 5, "medium": 7, "high": 10, "critical": 12}
    level = level_map.get(sigma_doc.get("level", "medium"), 7)
    tags = ",".join(sigma_doc.get("tags", []))

    mitre_ids = [
        t.split(".", 1)[1].upper().replace(".", ".")
        for t in sigma_doc.get("tags", [])
        if t.startswith("attack.t")
    ]
    mitre_blocks = "\n".join(
        f"      <id>{tid}</id>" for tid in mitre_ids
    ) or "      <id>T0000</id>"

    parent_sid = sigma_doc.get("_wazuh_parent_sid", "1002")
    detection = sigma_doc.get("detection", {})
    match_terms: list[str] = []
    for key, val in detection.items():
        if key in ("condition", "timeframe"):
            continue
        if isinstance(val, dict):
            for _, v in val.items():
                if isinstance(v, str):
                    match_terms.append(v)
                elif isinstance(v, list):
                    match_terms.extend(str(x) for x in v)
    match_block = (
        f"<match>{'|'.join(match_terms)}</match>" if match_terms else ""
    )

    return WAZUH_RULE_TEMPLATE.format(
        tags=tags,
        rule_id=100000 + numeric_id,
        level=level,
        parent_sid=parent_sid,
        description=description,
        mitre_blocks=mitre_blocks,
        match_block=match_block,
    )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--in", dest="in_dir", required=True)
    p.add_argument("--out-wazuh", dest="out_wazuh", required=True)
    args = p.parse_args()

    in_dir = Path(args.in_dir)
    out_dir = Path(args.out_wazuh)
    out_dir.mkdir(parents=True, exist_ok=True)

    rule_files = sorted(in_dir.glob("*.yml"))
    if not rule_files:
        print(f"No Sigma rules found in {in_dir}", file=sys.stderr)
        return 0

    combined = ['<!-- Generated by compile_sigma.py. Do not hand-edit. -->']
    for idx, src in enumerate(rule_files):
        doc = yaml.safe_load(src.read_text())
        xml = _sigma_to_wazuh(doc, idx)
        out = out_dir / f"{src.stem}.xml"
        out.write_text(xml)
        combined.append(xml)
        print(f"compiled {src.name} -> {out.name}")

    (out_dir / "_all_rules.xml").write_text("\n".join(combined))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
